PORT: 8080

DB:
  HOST: localhost
  PORT: 5432
  NAME: sequence_db
  USER: postgres
  PASSWORD: password
  MAX_IDLE_CONNS: 10
  MAX_OPEN_CONNS: 100
  MAX_LIFETIME_CONNS: 300
  SSL_MODE: disable

KAFKA:
  BROKERS: localhost:9092,localhost:9093
  TOPICS:
    EMAIL_JOBS: email-jobs
    FOLLOWUP_EVENTS: followup-events
    EMAIL_RETRIES: email-retries
    EMAIL_EVENTS: email-events
