PORT: GO_SEQUENCE_PORT

DB:
  HOST: GO_SEQUENCE_DB_HOST
  PORT: GO_SEQUENCE_DB_PORT
  NAME: GO_SEQUENCE_DB_NAME
  USER: GO_SEQUENCE_DB_USER
  PASSWORD: GO_SEQUENCE_DB_PASSWORD
  MAX_IDLE_CONNS: GO_SEQUENCE_DB_MAX_IDLE_CONNS
  MAX_OPEN_CONNS: GO_SEQUENCE_DB_MAX_OPEN_CONNS
  MAX_LIFETIME_CONNS: GO_SEQUENCE_DB_MAX_LIFETIME_CONNS
  SSL_MODE: GO_SEQUENCE_DB_SSL_MODE
